### ISSUE TITLE
Possible merge with stylefmt?

### ISSUE THREAD

**Issue by okonet** [hudochenkov/postcss-sorting#18]
[stylefmt](https://github.com/morishitter/stylefmt) looks promising but it lacks this feature. I'm wondering if this project can be a part or be used by stylefmt.

**Comment by hudochenkov** [comment]
I don't think we can merge it, but we can use postcss-sorting as dependency in stylefmt. There are some caveats we should think through. stylefml has no options, only stylelint config can change stylefmt behaviour. postcss-sorting has options and it's essential part of plugin.

**Comment by okonet** [comment]
Can https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-properties-order/README.md be used or these 2 configs are completely incompatible?

**Comment by hudochenkov** [comment]
These configs compatible only in simple situation like: `["transform", "top", "color"]`, array of properties. Otherwise they are not compatible.

**Comment by jeddy3** [comment]
> These configs compatible only in simple situation like: ["transform", "top", "color"], array of properties. Otherwise they are not compatible.

FYI, in `stylelint@7.0.0` [we're going to](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/release-planning.md) reduce the scope of `declaration-block-properties-order` to, as the name implies, check only the order of properties within a declaration block. Our hope is that the community develops a more powerful `block-structure` plugin, which is concerned with not only the order of declarations but that of nested (at-)rules, as well as the empty lines between things.

One possible option is for the community to base that plugin on your great work here. You could, for example, (with their help) provide a lint option within `postcss-sorting`. This would only warn of violations within the source, rather than modifying it. `stylehacks` [does something similar](https://github.com/ben-eb/stylehacks#lint), which we consume and expose as the [`no-browser-hacks`](https://github.com/stylelint/stylelint/blob/master/src/rules/no-browser-hacks/README.md) rule.

The `block-structure` plugin can have any option configuration (allowing you to keep your existing options), much in the same way as the [`stylelint-selector-bem-pattern`](https://github.com/davidtheclark/stylelint-selector-bem-pattern) plugin directly accepts the options of [`postcss-bem-linter`](https://github.com/postcss/postcss-bem-linter).

People would then be able to use the `block-structure` stylelint plugin within their CIs to check that each block is correctly structured. They could then use `postcss-sorting` to automatically fix those violations.

I thought I'd give you the heads-up in case this is something that would interest you :)

**Comment by hudochenkov** [comment]
@jeddy3 Thank you for an excellent suggestion what to do and tips! I am very interested in making `postcss-sorting` part of a `stylelint` and `stylefmt`. I'll fix some bugs and then will start to work on integration to `stylelint`.

**Comment by paazmaya** [comment]
http://stylelint.io/user-guide/rules/declaration-block-properties-order/ has the simplest option to use `"alphabetical"` sorting.
While `stylefmt` has this feature supported for the more complicated use cases, the alphabetical sorting is missing.
Easiest way to add it in `stylefmt` would be via this `postcss-sorting`, since it is already used for the giving rule.

Would be possible to add `"alphabetical"` as one of the `sort-order` configurations?

**Comment by hudochenkov** [comment]
@paazmaya it's possible, but this order has low priority right now.

**Comment by hudochenkov** [comment]
As of now stylefmt has postcss-sorting integrated. It uses [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) options.

In May or June, we'll release stylelint with autofixing, and I'll add autofixing to stylelint-order.
