### ISSUE TITLE
File config for sorting styles

### ISSUE THREAD

**Issue by ghost** [hudochenkov/postcss-sorting#23]
It will be usefull with file config with rules for sorting styles. For example we can use filename with .psortingrc file with rules for sorting

**Comment by hudochenkov** [comment]
I'll think about it. Meanwhile you can use external file for storing a config if you use Gulp or Grunt. You can see an example of using external config in Gulp at this repository https://github.com/wildbit/postcss-sorting-config-wildbit

**Comment by uharbachou** [comment]
Yeah, thanks a lot, right now i use it how in gulp example. It not so hard, but easier file with specific extension for configuration.

**Comment by danielbayley** [comment]
See also my proposed algorithm for [atom-postcss-sorting](https://github.com/lysyi3m/atom-postcss-sorting/pull/13/commits/b0f7367401c4521441ff0709a19ae28a6b02912b).

**Comment by joemaller** [comment]
Being able to drop a config dotfile in a project repo would be great, though this seems like something that really needs to be solved upstream by PostCSS.

Long, relevant discussion about adding dotfile cofigs:  postcss/postcss#477

A few projects I'm working on use CSSComb over PostCSS-Sorting, specifically because of the easily shared `.csscomb.json` config file. There do seem to be a lot of those dotfiles these days, but at least they're explicit and easy to understand.

**Comment by Meshock** [comment]
Maybe, as idea, should make the ability to use sort settings from config stylelint?

**Comment by hudochenkov** [comment]
I won't add config support for postcss-sorting. But there are good news!

We are working on adding autofixing functionality to [stylelint](https://stylelint.io/). I'll add sorting autofixing to [`stylelint-order`](https://github.com/hudochenkov/stylelint-order). So in the future you can use only one tool to lint and format your stylesheets — stylelint. It means, you'll have config support, and you'll only one config. I expect it will happen in summer.
