### ISSUE TITLE
Respecting stylelint-order value for emptyLineBefore

### ISSUE THREAD

**Issue by wroughtec** [hudochenkov/postcss-sorting#47]
I currently use your stylelint-order to help keep our css in a clear group and structure using a line break between each group.

I just recently updated postcss-sorting to the v 2 branch as I had hoped to share the config so I was not maintaining 2 different configs however I noticed a slight discrepancy:

In stylelint-order you use the "always" value for the empty line:
```
[
    {
        "emptyLineBefore": "always",
        ....
```

While in postcss-sorting it is just a boolean
```
"properties-order": [
        {
            "emptyLineBefore": true,
            ....
```

This results in an error being logged:
postcss-sorting: Invalid "properties-order" option value

Is it possible that these options could match as this will cut down on extra code.

**Comment by hudochenkov** [comment]
Had you shared config somehow between stylelint-order and postcss-sorting before? Do you share it somehow now?

There is no way to just use .stylelintrc for postcss-sorting, because stylelint's rules and this plugin's rules have different names.

Stylelint:

```js
{
    "order/declaration-block-order": [],
    "order/declaration-block-property-groups-structure": []
}
```

postcss-sorting:

```js
{
    "order": [],
    "properties-order": []
}
```

So it already needs some config conversion. Since it needs conversion, it can use more simple values then. My goal is to make independent software, which can be used by itself without stylelint. Config is friendlier for people not familiar with stylelint.

But I kept in mind stylelint when was developing v2. Stylelint's config can be used by this plugin, but after a little conversion.

There is a tool to format style sheets with stylelint config — [stylefmt](https://github.com/morishitter/stylefmt/). I'm going to add stylelint-order rules to it, and it will use postcss-sorting internally.

**Comment by wroughtec** [comment]
True if you add stylelint in directly like that they do not match but internally the blobs are almost apart from  same and its easy to set the rules without needing the entire blob:

```'properties-order': config.rules['order/declaration-block-property-groups-structure']```

In v1 no I could not you the rules directly (well I could in an earlier version of stlyelint) and had to write some rules to translate the order which was why I was glad that v2 came out and pretty much respected the rule shape.

Yes I already use stylefmt as well so if you will be adding these rules there as well then potentially I can remove the sorting from my build step however I just thought these match as they are now would have been useful.

**Comment by hudochenkov** [comment]
@wroughtec I won't change this, because I'll drop these options altogether in the next major version in favor of stylelint's soon coming autofixing.

stylefmt supports stylelint-order now.
