### ISSUE TITLE
Using astroturf composes

### ISSUE THREAD

**Issue by naxxateux** [hudochenkov/postcss-sorting#93]
Hi! Fantastic plugin you got here ;-)

I wonder how one can use it with astroturf composes (https://github.com/4Catalyzer/astroturf#composition-variables-etc)? I've tried to use it but got the `Unknown word` error. Should I put `composes` to `properties-order` array?

**Comment by hudochenkov** [comment]
What is the content of the file? How do you run this plugin?

**Comment by naxxateux** [comment]
I run this plugin in pre-commit hook (using lint-staged) like this (.lintstagedrc):
```
{
  "{}/**/*.js": [
    ...,
    "./postcss/sort"
  ]
}
```

My ./postcss/sort looks like this:
```
let order = []

for (let i of recess.rules['order/properties-order']) {
  order = order.concat(i.properties)
}

let sorter = postcss([sorting({ 'properties-order': order })])

...

sorter.process(...)
```

My component code is in .js file:
```
import textStyles from './text-styles'

let Name = styled.div`
  margin-right: 10px;
  composes: ${textStyles.mainBold};
`
```

**Comment by hudochenkov** [comment]
You need to use use custom syntax for PostCSS, because PostCSS can't parse CSS-in-JS. You would need to use [`@stylelint/postcss-css-in-js`](https://github.com/stylelint/postcss-css-in-js), but it doesn't work with PostCSS 8.

```js
const syntax = require("postcss-syntax")({
	jsx: require('@stylelint/postcss-css-in-js'),
});

sorter.process(source, { syntax: syntax })
```

I never tried this snippet, but theoretically this should work.

Alternatively you could use [stylelint](https://stylelint.io/) (with `--fix` flag) and [stylelint-order](https://github.com/hudochenkov/stylelint-order). stylelint has CSS-in-JS support.

**Comment by naxxateux** [comment]
Thnx! I will try use your solutions.
